# Generated by Django 4.0.2 on 2022-04-05 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_for_activation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
