# Generated by Django 3.2.4 on 2022-05-13 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_like'),
        ('users', '0003_user_token_for_activation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookmarkedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('L', "O'qiyapman"), ('W', "O'rganishni xohlayman"), ('K', 'Bilaman')], default='L', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.generallink')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
