# Generated by Django 4.0.2 on 2022-04-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_company_companytype_section_tag_linktype_generallink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='Uzbekistan', max_length=100),
            preserve_default=False,
        ),
    ]
