# Generated by Django 4.0.2 on 2022-04-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generallink',
            name='url',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
    ]
