# Generated by Django 3.2 on 2022-04-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_generallink_author_alter_generallink_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='short_description',
            field=models.CharField(default='-', max_length=150),
            preserve_default=False,
        ),
    ]
