# Generated by Django 3.2 on 2022-05-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_generallink_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='generallink',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
